### ISSUE TITLE
Manage versions for the image

### ISSUE THREAD

**Issue by aurelien-reeves** [cucumber/build#10]
In order to be able to have repeatable builds, we need to properly version images.

Automate the release process so that the changelog is updated, a git tag is created, and the image is properly tagged and published.

**Comment by aslakhellesoy** [comment]
We should publish the `latest` tag as well as the version tag so consumers can decide whether they want to pin or just use latest.

**Comment by mattwynne** [comment]
See #21 - should help with this, though that change still leaves CHANGELOG update to be done by hand.

**Comment by aslakhellesoy** [comment]
Can we close this now? We've been publishing versioned images for a while now.
