### ISSUE TITLE
Check hash of all dependencies installed via curl/wget

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/build#14]
To gaurd against supply chain attacks such as the one executed against CodeCov it would be prudent to verify the hash of all scripts downloaded by curl or wget before adding them to the docker image.

https://about.codecov.io/security-update/

**Comment by mattwynne** [comment]
@mpkorstanje I figured it was a good idea to do this before we merge https://github.com/cucumber/cucumber-build/pull/21 so here's my attempt in #22. Feedback appreciated!
