### ISSUE TITLE
sbt debian has gone away

### ISSUE THREAD

**Issue by mattwynne** [cucumber/build#15]
Trying to build the container locally I get this error:

```
 => ERROR [22/26] RUN curl -SL --output sbt.deb https://dl.bintray.com/sb  0.4s
------
 > [22/26] RUN curl -SL --output sbt.deb https://dl.bintray.com/sbt/debian/sbt-1.3.13.deb     && dpkg -i sbt.deb     && rm -f sbt.deb:
#26 0.184   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
#26 0.184                                  Dload  Upload   Total   Spent    Left  Speed
100    10  100    10    0     0     56      0 --:--:-- --:--:-- --:--:--    56
#26 0.377 dpkg-deb: error: 'sbt.deb' is not a Debian format archive
#26 0.377 dpkg: error processing archive sbt.deb (--install):
#26 0.377  dpkg-deb --control subprocess returned error exit status 2
#26 0.386 Errors were encountered while processing:
#26 0.386  sbt.deb
------
executor failed running [/bin/sh -c curl -SL --output sbt.deb https://dl.bintray.com/sbt/debian/sbt-1.3.13.deb     && dpkg -i sbt.deb     && rm -f sbt.deb]: exit code: 1
```

It [looks like](https://www.scala-sbt.org/1.x/docs/Installing-sbt-on-Linux.html#Ubuntu+and+other+Debian-based+distributions) this is because JFrog Bintray is being turned off. So we need to fetch the package from somewhere else.

**Comment by ciaranmcnulty** [comment]
@gaeljw do you know a better source for this? I see you added the binary DL to the Dockerfile

**Comment by gaeljw** [comment]
Indeed, new source to download sbt would be https://repo.scala-sbt.org/scalasbt/debian.

You can also take the opportunity of this change to use latest version, that is https://repo.scala-sbt.org/scalasbt/debian/sbt-1.5.1.deb
(a new sbt binary will still be able to build old sbt projects)
