### ISSUE TITLE
Reduce image size

### ISSUE THREAD

**Issue by gaeljw** [cucumber/build#4]
I just noticed that the cucumber-build image takes more than 4GB.

This seems unreasonable considering what it is used for.

```
$ docker image ls
REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
cucumber/cucumber-build       latest              2e90d1cac481        4 weeks ago         4.31GB
```

IMHO we should target a size inferior to 500MB.

What do you think? I can have a look when I have some time.

**Comment by mpkorstanje** [comment]
I picked a fairly large base image because we have to install a fairly large number of different tools. Each individual tool has a small base image it works on well but there is usually another that is almost impossible to install.

**Comment by mpkorstanje** [comment]
Feel free to try and make everything else smaller though.

**Comment by gaeljw** [comment]
Ah okay, I didn't notice that the image contains everything to build in every language.
Indeed, the Ubuntu base image doesn't count for much of the size in the end.

In its current version, the image size comes from:
1. Tools (Bash, JDK, Perl, Ruby...): 1.91 GB
1. .NET cache: 1.08 GB
1. .NET Core SDK: 357 MB
1. Ruby configuration: 175 MB
1. Elixir: 164 MB
1. Universe repository: 137 MB
1. Go/Splitsh: 126 MB
1. NPM: 96 MB
1. Pip/Twine/Behave: 80 MB 
1. Ubuntu: 73 MB

My opinion is that we should maybe have a base image with the common tools and then one image per language (one for JVM, one for JS, ...).

**Comment by mpkorstanje** [comment]
You can make a separate one for just Java. And extract the java parts to a separate file and reuse them in both. We'll still need the aggregate for the monorepo.

**Comment by gaeljw** [comment]
Ah right, didn't think of the monorepo! Let's keep it like this for now then.

I just have to delete and download the image every time I need it, otherwise I don't have enough space in my Docker directory but that's my own problem :laughing:

**Comment by gaeljw** [comment]
See #18
