### ISSUE TITLE
Use layer caching to speed up Build / Release workflows

### ISSUE THREAD

**Issue by mattwynne** [cucumber/build#45]
The [`Build`](https://github.com/cucumber/build/actions/workflows/build.yaml) workflow, which is a required status check, takes about an hour to run.

When we run the [`Release`](https://github.com/cucumber/build/actions/workflows/release.yaml) workflow we have to rebuild the container again from scratch, because we don't have any of the layers cached.

[This blog post](https://evilmartians.com/chronicles/build-images-on-github-actions-with-docker-layer-caching#the-cache-dance-off) could be a good starting point for how to use GitHub's cache.

**Comment by mattwynne** [comment]
I've merged #46 so we can watch it perform.

**Comment by mattwynne** [comment]
Don't know why this isn't working. It all looks correct to me, but the images are still being completely rebuilt every time.

**Comment by ciaranmcnulty** [comment]
This may be improved by #69 (cached build in seconds)

**Comment by mattwynne** [comment]
Shall we close this now @ciaranmcnulty ?

**Comment by ciaranmcnulty** [comment]
Think so, yeah

**Comment by ciaranmcnulty** [comment]
@mattwynne although thinking about it, what's the point of a nightly cached build?

**Comment by mattwynne** [comment]
I guess the nightly build should not be cached, but it would be nice if the `on.push` build were faster.

**Comment by mattwynne** [comment]
As we gradually [dismantle the monorepo](https://github.com/orgs/cucumber/projects/12), this image becomes less and less important anyway. I think we can figure out a new approach if we want to be able to do polyglot builds locally of libraries like gherkin once they're out of the monorepo.

**Comment by ciaranmcnulty** [comment]
We could `--no-cache` the nightly

I've been holding off on optimising the cucumber/common build because of the promised monorepo future :)

**Comment by ciaranmcnulty** [comment]
>  if we want to be able to do polyglot builds locally of libraries

A buildkit + multiple container approach would be good here. Is it worth prototyping inside, say, Messages?

**Comment by mattwynne** [comment]
I think an existing stand-alone polyglot repo like cucumber-expressions would be a better place to prove the concept, then when we have extracted messages to its own repo we can try it there with more languages/build environments.

**Comment by aslakhellesoy** [comment]
Is there a problem with the cucumber-expressions build process we need to address? I’m fine with the way it currently works.

**Comment by mattwynne** [comment]
Not particularly. The suggestion is that we may, for some polyglot projects (e.g. gherkin), want a way to run tests across all/several platforms locally, without having to push and wait for CI for feedback, or rely on this big docker image. I think cucumber-expressions would be a good place to try that kind of thing out.

**Comment by ciaranmcnulty** [comment]
Expressions is fine IMO because there's not anything generated

The complexity has in the past come from something like messages where Ruby+target are used, or Gherkin where dotnet+target were used

I don't know how we are tackling the DX of running the tests locally for Expressions?
