### ISSUE TITLE
Install Berp 1.3.0 using dotnet tools

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/build#80]
So use:

```
dotnet tool update Berp --version 1.3.0 --tool-path /usr/bin
```
https://github.com/cucumber/common/blob/ec9a174170ae9abf936e40b5e4f0702daf75346e/gherkin/java/default.mk#L74-L77

This important because .Net 5.0 has been deprecated and is no a bit harder to install on Ubuntu. So we may still have to use the image for a while.

**Comment by ehuelsmann** [comment]
This is solved in https://github.com/cucumber/build/commit/fd42069ff95b5045cb8bdea021397073ea9f7696
